[package]
name = "x870e-lcd-patcher"
description = "Firmware inspection, verification, and patching utility for ASUS ROG Crosshair X870E Motherboard LCD Panel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
