[package]
name = "x870e-lcd-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "x870e-lcd"
path = "src/main.rs"

[dependencies]
x870e-lcd-core = { path = "../x870e-lcd-core" }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true }
