[package]
name = "x870e-lcd-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rusb = { workspace = true }
hidapi = { workspace = true }
image = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sysinfo = { workspace = true }
jpeg-encoder = "0.7.1"
